eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: proxy-server-api-gateway
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411