eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9090
spring:
  application:
    name: addition-service
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
